### ISSUE TITLE
Unexpected value 'MyDatePickerModule' imported by the module 'DevModule'

### ISSUE THREAD

**Issue by lzm420241** [kekeh/mydatepicker#50]

**Comment by kekeh** [comment]
I had earlier similar problem in my demo page app. I updated some of the dependencies in the **package.json**. Check the link below. Maybe updating **webpack** version from **1.13.0** to **1.13.2** solved the issue.

https://github.com/kekeh/mydatepicker/blob/gh-pages/package.json

After updating package.json app worked ok.

Webpack **config** of the same project is here: https://github.com/kekeh/mydatepicker/blob/gh-pages/config/webpack.build.js

**Comment by lzm420241** [comment]
but when i updated webpack from 1.13.0 to 1.13.2,it still does not work!
here is my json file 
`{
  "name": "angular2-webpack",
  "version": "1.0.0",
  "description": "A webpack starter for angular 2",
  "scripts": {
    "start": "gulp css && webpack-dev-server --inline --progress --port 8081",
    "test": "karma start",
    "build": "gulp css && rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail",
    "postinstall": "typings install"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "core-js": "^2.4.1",
    "mydatepicker": "0.0.37",
    "ng2-cookies": "^1.0.2",
    "ng2-pagination": "^0.4.1",
    "rxjs": "5.0.0-beta.11",
    "zone.js": "^0.6.17"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "angular2-template-loader": "^0.4.0",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "gulp": "^3.9.1",
    "gulp-sass": "2.3.2",
    "gulp-sourcemaps": "^1.6.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.0",
    "karma-phantomjs-launcher": "^1.0.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "style-loader": "^0.13.1",
    "ts-loader": "^0.8.1",
    "typescript": "^1.8.10",
    "typings": "^1.0.4",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0"
  }
}
`

**Comment by kekeh** [comment]
Have you any special reason to use RC 6 version of Angular? Latest version of Angular is 2.0.1.

You can check all outdated versions by running: **npm outdated**

After update versions to the package.json run command: **npm update**

**Comment by scottwio** [comment]
I have this same issue when using angular-cli https://github.com/angular/angular-cli/issues/1831

**Comment by lzm420241** [comment]
@kekeh i do this,but it still does not work! only tips:`Unexpected value 'MyDatePickerModule' imported by the module 'DevModule'`

**Comment by lzm420241** [comment]
@kekeh  when i use source code as module to use,it still does not work ,and tips:compiler.umd.js?9df7:3137 Uncaught Error: Expected 'styles' to be an array of strings.

**Comment by lzm420241** [comment]
@kekeh i use source code as module ,and it worked ,but it seems not to set hours and min,second,right?

**Comment by kekeh** [comment]
@lzm420241 
If you got this: Uncaught Error: Expected 'styles' to be an array of strings
            {
                test: /\.css$/,
                loader: "to-string-loader!css-loader"
            }
In your webpack config implement the **css loader** this way. Like here https://github.com/kekeh/mydatepicker/blob/master/config/webpack.dev.js lines between 28 -31. Then install **to-string-loader** and **css-loader** if needed.
**npm install to-string-loader --save-dev**
**npm install css-loader --save-dev**

After that there is no need to replace styles with stylesUrl.

**Comment by ghetolay** [comment]
I'm having same error with all dependencies up to date (angular 2.0.2 and webpack 1.13.1).
Also it does no seem related to webpack, the error is caused by angular compiler (on browser not using angular cli).

investigating for the next hour...

**Comment by ghetolay** [comment]
Ok my bad it's indeed related to webpack : `require('@angular/core')` is loading a different instance.
Now let's find out why it end up with it's own instance of angular core...

**Comment by ghetolay** [comment]
Ok found out.

@kekeh You are publishing your `node_modules` folder with npm.

This was pretty obvious but when we look for bugs we often forget the basics :)

**Comment by kekeh** [comment]
I am publishing on only these files/folders to npm (version 0.0.37):
  "files": [
    "LICENSE",
    "package.json",
    "README.md",
    "src/my-date-picker",
    "index.ts",
    "index.js",
    "dist"
  ],

Or what do you mean?

**Comment by ghetolay** [comment]
Well indeed I just did a fresh `npm install mydatepicker` an there is no `node_modules` folder.
I absolutely don't know how I ended up having a `node_modules` folder inside `mydatepicker` but this was the cause of this same error.

@lzm420241 can you check if this is your case too ?

**Comment by scottwio** [comment]
Same problem here when ever I do an npm install for mydatepicker it's creating it's own node_modules folder

http://d.pr/i/12xX4

**Comment by scottwio** [comment]
Ok I think this is because the module requires angular 2.0.1 and up and I had my version fixed at 2.0.0 and it also seems to be require reflect-metadata 0.1.8 and up, I had version 0.1.3 which is the version angular 2.0.0 requires. Npm creates a new node_modules folder because dependencies can not be matched creating a new instance of angular common. 

To fix this going forward @angular should require a min of 2.0.0 in package.json and not higher.

**Comment by kekeh** [comment]
@scottwio 
Probably in the package.json of mydatepicker I have to move all modules from the **dependencies** to the **devDependencies**.

After that the node_modules under the mydatepicker is not created in any case.

**Comment by arsalan-ahmed-10p** [comment]
@kekeh I tried almost all the methods described in this issue thread but its not working.
Still getting the following error:
_Uncaught Error: Unexpected value 'MyDatePickerModule' imported by the module 'AppModule'_

**Comment by kekeh** [comment]
@arsalan-ahmed-10p 

You have to use Angular 2.0.1 or 2.0.2 in your own package.json. When you have updated versions to package.json run: **npm update**

When update is ready delete the mydatepicker folder from the node_modules and run **npm install mydatepicker@0.0.37 --save-dev**. After installation there should not be node_modules folder under the node_modules/mydatepicker.

You can set also **cache: false** in your webpack config file.

Try build your project.

**Comment by arsalan-ahmed-10p** [comment]
@kekeh 

I updated my **@angular/core to 2.0.1**
Removed node_modules folder (rm -rf node_modules) and then did an **npm install**.

It worked! I guess I just had to update Angular to 2.0.1.

Thanks a bunch.

**Comment by kekeh** [comment]
Version **0.0.38** fix this issue. Thanks all of you helping me to solve issue.

**Comment by sadeghipour** [comment]
😢 

We still have problem:

EXCEPTION: Uncaught (in promise): Error: Unexpected value 'MyDatePickerModule' imported by the module 'DomModule'
packet.json:

"dependencies": {
    "@angular/common": "~2.1.2",
    "@angular/compiler": "~2.1.2",
    "@angular/compiler-cli": "~2.1.2",
    "@angular/core": "~2.1.2",
    "@angular/forms": "~2.1.2",
    "@angular/http": "~2.1.2",
    "@angular/platform-browser": "~2.1.2",
    "@angular/platform-browser-dynamic": "~2.1.2",
    "@angular/platform-server": "~2.1.2",
    "@angular/router": "~3.1.2",
    "@angular/upgrade": "~2.1.2",
    "@angularclass/bootloader": "~1.0.1",
    "@angularclass/idle-preload": "~1.0.4",
    "angular2-express-engine": "~2.1.0-rc.1",
    "angular2-platform-node": "~2.1.0-rc.1",
    "angular2-text-mask": "^3.0.0",
    "angular2-universal": "~2.1.0-rc.1",
    "angular2-universal-polyfills": "~2.1.0-rc.1",
    "async": "^2.1.4",
    "body-parser": "^1.15.2",
    "btoa": "^1.1.2",
    "compression": "^1.6.2",
    "express": "^4.14.0",
    "js.clone": "0.0.3",
    "methods": "~1.1.2",
    "morgan": "^1.7.0",
    "mydatepicker": "^1.7.7",
    "preboot": "~4.5.2",
    "request": "^2.79.0",
    "rxjs": "5.0.0-beta.12",
    "webfontloader": "^1.6.26",
    "zone.js": "~0.6.26"
  },
  "devDependencies": {
    "@ngtools/webpack": "~1.1.7",
    "@types/body-parser": "0.0.29",
    "@types/compression": "0.0.29",
    "@types/cookie-parser": "^1.3.29",
    "@types/express": "^4.0.32",
    "@types/express-serve-static-core": "^4.0.33",
    "@types/hammerjs": "^2.0.32",
    "@types/mime": "0.0.28",
    "@types/morgan": "^1.7.32",
    "@types/node": "^6.0.38",
    "@types/serve-static": "^1.7.27",
    "@types/webfontloader": "^1.6.27",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "^2.2.4",
    "cookie-parser": "^1.4.3",
    "imports-loader": "^0.6.5",
    "json-loader": "^0.5.4",
    "mydatepicker": "^1.7.7",
    "nodemon": "^1.10.0",
    "raw-loader": "^0.5.1",
    "reflect-metadata": "0.1.8",
    "rimraf": "^2.5.4",
    "string-replace-loader": "^1.0.5",
    "ts-helpers": "^1.1.2",
    "ts-node": "^1.3.0",
    "typescript": "2.0.2",
    "v8-lazy-parse-webpack-plugin": "^0.3.0",
    "webpack": "2.1.0-beta.27",
    "webpack-bundle-analyzer": "1.4.1",
    "webpack-dev-middleware": "^1.8.4",
    "webpack-dev-server": "2.1.0-beta.11",
    "webpack-merge": "~0.16.0"
  }


in module:
import { MyDatePickerModule } from 'mydatepicker';
@NgModule({
    imports: [CommonModule,FormsModule,RouterModule,ReactiveFormsModule,MyDatePickerModule],
