### ISSUE TITLE
Problem on integration with Ionic2

### ISSUE THREAD

**Issue by juansaab** [kekeh/mydatepicker#92]
Thanks for this module. I have been using it on an Ionic2 project with no issues on the navigator. However, when I try to build the project for iOS platform I'm getting the following error:

```
Error: Error at .../.tmp/node_modules/mydatepicker/src/my-date-picker/directives/my-date-picker.input.directive.ngfactory.ts:23:20
[16:09:56]  Property 'inputFocus' does not exist on type 'InputFocusDirective'. 
[16:09:56]  ngc failed 
[16:09:56]  ionic-app-script task: "build" 
[16:09:56]  Error: Error
```

Then after I try to run the application on the simulator I got this error.

```
Error: Module parse failed: .../node_modules/mydatepicker/src/my-date-picker/my-date-picker.module.ts Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
| import { InputFocusDirective } from "./directives/my-date-picker.input.directive";
| 
| @NgModule({
|     imports: [CommonModule],
|     declarations: [MyDatePicker, InputFocusDirective],, http://192.168.0.5:8100/build/main.js, Line: 67
I 
```

I know Ioinic is not the target of the module but any help will be appreciated.

Thank you!

**Comment by kekeh** [comment]
There was similar error here: https://github.com/kekeh/mydatepicker/issues/84

but I don't know how it was fixed.

**Comment by kekeh** [comment]
I did fix to the **InputFocusDirective**, but I don't know does it fix the problem.

New version is 1.0.17.

**Comment by juansaab** [comment]
Hello,

I already did the inputFocus declaration so compiling can be done. However, the second problem is still showing when building for production. I do think it is related to webpacking or something that is done only during the "build for production" process.

```
Error: Module parse failed: .../node_modules/mydatepicker/src/my-date-picker/my-date-picker.module.ts Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
| import { InputFocusDirective } from "./directives/my-date-picker.input.directive";
| 
| @NgModule({
|     imports: [CommonModule],
|     declarations: [MyDatePicker, InputFocusDirective],, http://192.168.0.5:8100/build/main.js, Line: 67
I 
```

**Comment by kekeh** [comment]
I am using this kind of webpack config in the demo page: https://github.com/kekeh/mydatepicker/blob/gh-pages/config/webpack.build.js

Seems that the typescript loader is missing from the webpack config. For example **'awesome-typescript-loader'**, **'angular2-template-loader'** like below:

```javascript
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader', 'angular2-template-loader']
            },
            .....
        ]
}
```

Check from the package.json are these two already installed. If not you can install them:
npm install awesome-typescript-loader --save-dev
npm install angular2-template-loader --save-dev

then add the typescript loader like above to the webpack.config.js

Check also the tsconfig.json file. One example from the demo page: https://github.com/kekeh/mydatepicker/blob/gh-pages/tsconfig.json

Here is Angular2 webpack tutorial: https://angular.io/docs/ts/latest/guide/webpack.html
